type ProductTypeResponse = {
  product_id: string;
  name: string;
  price: string;
  image: string | null;
  description: string;
  meta_title: string;
  meta_description: string;
  meta_keyword: string;
  tag: string;
  model: string;
  sku: string;
  upc: string;
  ean: string;
  jan: string;
  isbn: string;
  mpn: string;
  location: string;
  quantity: string;
  stock_status: string | null;
  manufacturer_id: string | null;
  manufacturer: string | null;
  special: string | null;
  reward: string | null;
  points: string;
  tax_class_id: string;
  date_available: string;
  weight: string;
  weight_class_id: string;
  length: string;
  width: string;
  height: string;
  length_class_id: string;
  subtract: string;
  rating: number;
  reviews: number;
  minimum: string;
  sort_order: string;
  status: string;
  date_added: string;
  date_modified: string;
  viewed: string;
};

export type ProductsTypeResponse = {
  list: ProductTypeResponse[];
  total: number;
};

export type ProductType = {
  id: string;
  name: string;
  price: number;
  oldPrice: number;
  image?: string;
  description: string;
  metaTitle: string;
  metaDescription: string;
  metaKeyword: string;
  tag: string;
  model: string;
  sku: string;
  upc: string;
  ean: string;
  jan: string;
  isbn: string;
  mpn: string;
  location: string;
  quantity: string;
  stockStatus?: string;
  manufacturerId?: string;
  manufacturer?: string;
  special?: string;
  reward?: string;
  points: string;
  taxClassId: string;
  dateAvailable: string;
  weight: string;
  weightClassId: string;
  length: string;
  width: string;
  height: string;
  lengthClassId: string;
  subtract: string;
  rating: number;
  reviews: number;
  minimum: string;
  sortOrder: string;
  status: string;
  dateAdded: string;
  dateModified: string;
  viewed: string;
};
