name: Node.js CD

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    name: Deploy using ssh
    steps:
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_SERVER_HOST }}
          username: ${{ secrets.DEPLOY_SERVER_USERNAME }}
          key: ${{ secrets.DEPLOY_SERVER_KEY }}
          port: ${{ secrets.DEPLOY_SERVER_PORT }}
          script: |
            cd ~/lampastar/lampastar-store-ssr
            git pull origin master
            git status
            npm ci
            export NODE_OPTIONS="--max_old_space_size=8192"
            npm run build:prod
            pm2 restart ${{ secrets.DEPLOY_SERVER_APP_ID }}
